const actionTypes = {
  FETCH_REQUEST_QUOTES: 'FETCH_REQUEST_QUOTES',
  FETCH_SUCCESS_QUOTES: 'FETCH_SUCCESS_QUOTES',
  FETCH_ERROR_QUOTES: 'FETCH_ERROR_QUOTES',

  FETCH_RANDOM_QOUTE_REQUEST: 'FETCH_RANDOM_QOUTE_REQUEST',
  FETCH_RANDOM_QOUTE_SUCCESS: 'FETCH_RANDOM_QOUTE_SUCCESS',
  FETCH_RANDOM_QOUTE_ERROR: 'FETCH_RANDOM_QOUTE_ERROR',

  FETCH_RANDOM_AUTHOR_QOUTE_REQUEST: 'FETCH_RANDOM_AUTHOR_QOUTE_REQUEST',
  FETCH_RANDOM_AUTHOR_QOUTE_SUCCESS: 'FETCH_RANDOM_AUTHOR_QOUTE_SUCCESS',
  FETCH_RANDOM_AUTHOR_QOUTE_ERROR: 'FETCH_RANDOM_AUTHOR_QOUTE_ERROR',
};

export default actionTypes;
